---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../reference-crs/required/gitops/
  - https://github.com/openshift-kni/telco-reference/telco-hub/configuration/reference-crs/required/gitops?ref=release-4.20

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: hub-config
    path: init-argocd-app.yaml
#  - target:
#      group: ""
#      version: v1
#      kind: ConfigMap
#      name: argocd-tls-certs-cm
#    path: argocd-tls-certs-cm-patch.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: clusters
    path: clusters-app.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: policies
    path: policies-app.yaml
