# kustomization file including different overays over the
# reference crs
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # if you use LocalStorage operator, edit and configure the patch
  # - jpena-hub-overlay/lso/
  # Using the LVMS operator, with storageClass "lvms-vg1"

  # if you use ODF, edit and configure storage settings
  #- jpena-hub-overlay/odf/

  # other not optional overlays
  - jpena-hub-overlay/gitops/
  - jpena-hub-overlay/acm/
  #- jpena-hub-overlay/registry/

  # mandatory resources not managed by any overlay
  #- reference-crs/required/talm/
  - https://github.com/openshift-kni/telco-reference/telco-hub/configuration/reference-crs/required/talm?ref=release-4.20


  # include this content if you want to include the argocd
  # configuration and apps for gitops ztp management of cluster
  # installation and configuration
  # - reference-crs/required/gitops/ztp-installation
  - https://github.com/openshift-kni/telco-reference/telco-hub/configuration/reference-crs/required/gitops/ztp-installation?ref=release-4.20

# Use the following for a connected environment
patches:
# from the reference we make it connected
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
    patch: |-
      - op: replace
        path: /spec/source
        value: redhat-operators
  - target:
      group: operator.open-cluster-management.io
      version: v1
      kind: MultiClusterHub
      name: multiclusterhub
    patch: |-
      - op: replace
        path: /metadata/annotations/installer.open-cluster-management.io~1mce-subscription-spec
        value: '{"source": "redhat-operators", "installPlanApproval": "Automatic"}'
      - op: replace
        path: /metadata/annotations/installer.open-cluster-management.io~1oadp-subscription-spec
        value: '{"source": "redhat-operators", "installPlanApproval": "Automatic"}'
  - target:
      group: config.openshift.io
      version: v1
      kind: OperatorHub
      name: cluster
    patch: |-
      - op: replace
        path: /spec/disableAllDefaultSources
        value: false
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: clusters
    path: jpena-hub-overlay/gitops/clusters-app.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: policies
    path: jpena-hub-overlay/gitops/policies-app.yaml
