---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- ../../reference-crs/optional/odf-internal/
  - https://github.com/openshift-kni/telco-reference/telco-hub/configuration/reference-crs/optional/odf-internal?ref=release-4.20

patches:
  - target:
      group: ocs.openshift.io
      version: v1
      kind: StorageCluster
      name: ocs-storagecluster
    path: options-storage-cluster.yaml
