---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ../../reference-crs/optional/lso/
  - https://github.com/openshift-kni/telco-reference/telco-hub/configuration/reference-crs/optional/lso?ref=release-4.20

patches:
  - target:
      group: local.storage.openshift.io
      version: v1
      kind: LocalVolume
      name: local-disks
    path: local-storage-disks-patch.yaml
